{% set data = load_setup_py_data() %}

package:
  name: pyiwe
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - wheel
    - flake8
  run:
    - python
    - ete3>=3.*
    - biopython>=1.78
    - tqdm>=4.62.3
    - numpy>=1.19
    - pandas>=1.3.5
    - pillow>=8.4.0
    - seaborn>=0.11.2
    - matplotlib>=3.5.0
    - pyqt>=5.*
    - jupyter>=1.0.0

test:
  imports:
    - pyiwe

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  license_file: LICENSE
  summary: {{ data['description'] }}
  doc_source_url: https://github.com/alexander-pv/pyiwe/blob/main/README.rst
