name: Publish to Anaconda Cloud

on:
  workflow_dispatch:
    platform:
      description: 'Platform'
      default: 'ubuntu-latest'
      required: true

jobs:
  publish:
    runs-on: ${{ github.event.inputs.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: publish-to-conda
      uses: fcakyon/conda-publish-action@v1.3
      with:
        subdir: 'conda'
        anacondatoken: ${{ secrets.CONDA_SECRET }}
        platforms: 'win linux'